version: '3.7'

services:
  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - staticfiles:/backend/staticfiles
      - "./dist/media:/backend/media"
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  celery_worker:
    build:
      context: .
    env_file: '.env'
    command: 'celery -A core worker -B'
    volumes_from:
      - backend
    depends_on:
      - backend
  
volumes:
  staticfiles:
  database:
  redisdata:

